LOCAL_PATH:= $(call my-dir)

common_src_files := \
	VolumeManager.cpp \
	CommandListener.cpp \
	VoldCommand.cpp \
	NetlinkManager.cpp \
	NetlinkHandler.cpp \
	Volume.cpp \
	DirectVolume.cpp \
	logwrapper.c \
	Process.cpp \
	Ext4.cpp \
	Fat.cpp \
	Loop.cpp \
	Devmapper.cpp \
	ResponseCode.cpp \
	Xwarp.cpp \
	VoldUtil.c \
	fstrim.c \
	cryptfs.c

#+NATIVE_PLATFORM [FUNCTION_STORAGE_FOR_AUTOMOTIVE]
common_src_files += \
	NetworkVolume.cpp fusefs.cpp utils.c ntfsutils.c
#-NATIVE_PLATFORM

#+NATIVE_PLATFORM [FUNCTION_STORAGE_SUPPORT_CDROM]
common_src_files += \
	cdfs.cpp
#-NATIVE_PLATFORM

#+NATIVE_PLATFORM [FUNCTION_STORAGE_SUPPORT_NTFS]
common_src_files += \
	Ntfs.cpp
#-NATIVE_PLATFORM

#+NATIVE_PLATFORM [FUNCTION_STORAGE_TUXERA_PATCH]
common_src_files += \
	Filesystems.cpp ExFat.cpp HfsPlus.cpp 
#-NATIVE_PLATFORM

common_c_includes := \
	$(KERNEL_HEADERS) \
	system/extras/ext4_utils \
	external/openssl/include \
	external/sqlite/dist \
	external/stlport/stlport \
	bionic \
	external/scrypt/lib/crypto

common_shared_libraries := \
	libsysutils \
	libstlport \
	libcutils \
	liblog \
	libdiskconfig \
	libhardware_legacy \
	liblogwrap \
	libcrypto \
	libsqlite \
	libext4_utils \
	libcrypto

common_static_libraries := \
	libfs_mgr \
	libscrypt_static \
	libmincrypt

include $(CLEAR_VARS)

LOCAL_MODULE := libvold

LOCAL_SRC_FILES := $(common_src_files)

LOCAL_C_INCLUDES := $(common_c_includes)

#+NATIVE_PLATFORM [FUNCTION_STORAGE_FOR_AUTOMOTIVE]
LOCAL_CFLAGS += -DFUNCTION_STORAGE_FOR_AUTOMOTIVE
#-NATIVE_PLATFORM
#+NATIVE_PLATFORM [FUNCTION_STORAGE_SUPPORT_NTFS]
LOCAL_CFLAGS += -DFUNCTION_STORAGE_SUPPORT_NTFS
#-NATIVE_PLATFORM
#+NATIVE_PLATFORM [FUNCTION_STORAGE_SUPPORT_CDROM]
LOCAL_CFLAGS += -DFUNCTION_STORAGE_SUPPORT_CDROM
#-NATIVE_PLATFORM
#+NATIVE_PLATFORM [FUNCTION_STORAGE_TUXERA_PATCH] 
LOCAL_CFLAGS += -DFUNCTION_STORAGE_TUXERA_PATCH
#-NATIVE_PLATFORM
#+NATIVE_PLATFORM [PATCH_STORAGE_REMOVE_PREPARED_STAGE] 
LOCAL_CFLAGS += -DPATCH_STORAGE_REMOVE_PREPARED_STAGE
#-NATIVE_PLATFORM
#+NATIVE_PLATFORM [FUNCTION_DEFINE_USB_FORMAT] 
LOCAL_CFLAGS += -DFUNCTION_DEFINE_USB_FORMAT
#-NATIVE_PLATFORM
#+NATIVE_PLATFORM [FUNCTION_STORAGE_MOUNT_LARGEST_PARTITION] 
# false LOCAL_CFLAGS += -DFUNCTION_STORAGE_MOUNT_LARGEST_PARTITION
#-NATIVE_PLATFORM

#+NATIVE_PLATFORM [FUNCTION_STORAGE_SUPPORT_NTFS&&FUNCTION_STORAGE_TUXERA_PATCH]
ifeq ($(ENABLE_NTFS_EXFAT_READWRITE),true)
LOCAL_CFLAGS += -DFEATURE_ENABLE_NTFS_EXFAT_READWRITE
endif
#-NATIVE_PLATFORM

LOCAL_SHARED_LIBRARIES := $(common_shared_libraries)

LOCAL_STATIC_LIBRARIES := $(common_static_libraries)

LOCAL_MODULE_TAGS := eng tests

include $(BUILD_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE:= vold

LOCAL_SRC_FILES := \
	main.cpp \
	$(common_src_files)

LOCAL_C_INCLUDES := $(common_c_includes)

LOCAL_CFLAGS := -Werror=format

#+NATIVE_PLATFORM [FUNCTION_STORAGE_FOR_AUTOMOTIVE]
LOCAL_CFLAGS += -DFUNCTION_STORAGE_FOR_AUTOMOTIVE
#-NATIVE_PLATFORM
#+NATIVE_PLATFORM [FUNCTION_STORAGE_SUPPORT_NTFS]
LOCAL_CFLAGS += -DFUNCTION_STORAGE_SUPPORT_NTFS
#-NATIVE_PLATFORM
#+NATIVE_PLATFORM [FUNCTION_STORAGE_SUPPORT_CDROM]
LOCAL_CFLAGS += -DFUNCTION_STORAGE_SUPPORT_CDROM
#-NATIVE_PLATFORM
#+NATIVE_PLATFORM [FUNCTION_STORAGE_TUXERA_PATCH] 
LOCAL_CFLAGS += -DFUNCTION_STORAGE_TUXERA_PATCH
#-NATIVE_PLATFORM
#+NATIVE_PLATFORM [PATCH_STORAGE_REMOVE_PREPARED_STAGE] 
LOCAL_CFLAGS += -DPATCH_STORAGE_REMOVE_PREPARED_STAGE
#-NATIVE_PLATFORM
#+NATIVE_PLATFORM [FUNCTION_DEFINE_USB_FORMAT] 
LOCAL_CFLAGS += -DFUNCTION_DEFINE_USB_FORMAT
#-NATIVE_PLATFORM
#+NATIVE_PLATFORM [FUNCTION_STORAGE_MOUNT_LARGEST_PARTITION] 
# false LOCAL_CFLAGS += -DFUNCTION_STORAGE_MOUNT_LARGEST_PARTITION
#-NATIVE_PLATFORM

#+NATIVE_PLATFORM [FUNCTION_STORAGE_SUPPORT_NTFS&&FUNCTION_STORAGE_TUXERA_PATCH]
ifeq ($(ENABLE_NTFS_EXFAT_READWRITE),true)
LOCAL_CFLAGS += -DFEATURE_ENABLE_NTFS_EXFAT_READWRITE
endif
#-NATIVE_PLATFORM

LOCAL_SHARED_LIBRARIES := $(common_shared_libraries)

LOCAL_STATIC_LIBRARIES := $(common_static_libraries)

include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)

LOCAL_SRC_FILES:= vdc.c

LOCAL_MODULE:= vdc

LOCAL_C_INCLUDES := $(KERNEL_HEADERS)

LOCAL_CFLAGS := 

LOCAL_SHARED_LIBRARIES := libcutils

include $(BUILD_EXECUTABLE)
